import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcryptjs';
import { createHash } from 'crypto';
import { existsSync, readFileSync } from 'fs';
import { mkdir, writeFile } from 'fs/promises';
import { dirname, join, resolve } from 'path';
import sharp from 'sharp';
import { fileURLToPath } from 'url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const backendRoot = resolve(scriptDir, '..');
const repoRoot = resolve(backendRoot, '../..');

const envPath = join(backendRoot, '.env');
const rootEnvPath = join(repoRoot, '.env');
loadEnvFile(existsSync(envPath) ? envPath : existsSync(rootEnvPath) ? rootEnvPath : join(repoRoot, '.env.example'));

const prisma = new PrismaClient();

const demoUser = {
  id: 'demo-user',
  email: 'demo@stickerfoundry.local',
  displayName: 'Demo User',
  password: 'stickerfoundry123',
};

const demoPack = {
  id: 'demo-pack-classics',
  name: 'Foundry Classics',
  publisher: 'Sticker Foundry Demo',
  description: 'A tiny local demo pack generated by the Prisma seed script.',
};

const stickers = [
  {
    id: 'demo-sticker-pow',
    fileName: 'demo-pow.webp',
    label: 'POW',
    fill: '#ef4444',
    accent: '#facc15',
    emojis: ['\uD83D\uDCA5'],
    accessibilityText: 'Pow sticker',
  },
  {
    id: 'demo-sticker-wow',
    fileName: 'demo-wow.webp',
    label: 'WOW',
    fill: '#14b8a6',
    accent: '#ffffff',
    emojis: ['\uD83D\uDE2E'],
    accessibilityText: 'Wow sticker',
  },
  {
    id: 'demo-sticker-ok',
    fileName: 'demo-ok.webp',
    label: 'OK',
    fill: '#6366f1',
    accent: '#a7f3d0',
    emojis: ['\uD83D\uDC4D'],
    accessibilityText: 'OK sticker',
  },
];

async function main() {
  const dataDir = resolve(backendRoot, process.env.DATA_DIR ?? './data');
  const packDir = join(dataDir, 'packs', demoPack.id);
  await mkdir(packDir, { recursive: true });

  const passwordHash = await bcrypt.hash(demoUser.password, 12);
  const user = await prisma.user.upsert({
    where: { email: demoUser.email },
    update: {
      displayName: demoUser.displayName,
      passwordHash,
      isAdmin: true,
    },
    create: {
      id: demoUser.id,
      email: demoUser.email,
      displayName: demoUser.displayName,
      passwordHash,
      isAdmin: true,
    },
  });

  await prisma.pack.upsert({
    where: { id: demoPack.id },
    update: {
      name: demoPack.name,
      publisher: demoPack.publisher,
      description: demoPack.description,
      isPublic: true,
      imageDataVersion: String(Date.now()),
      ownerId: user.id,
    },
    create: {
      id: demoPack.id,
      ownerId: user.id,
      name: demoPack.name,
      publisher: demoPack.publisher,
      description: demoPack.description,
      isPublic: true,
    },
  });

  await prisma.sticker.deleteMany({
    where: {
      packId: demoPack.id,
      id: { in: stickers.map((sticker) => sticker.id) },
    },
  });

  const trayIcon = await renderTrayIcon();
  await writeFile(join(packDir, 'tray_icon.webp'), trayIcon);

  for (const [position, sticker] of stickers.entries()) {
    const buffer = await renderSticker(sticker);
    await writeFile(join(packDir, sticker.fileName), buffer);

    await prisma.sticker.create({
      data: {
        id: sticker.id,
        packId: demoPack.id,
        fileName: sticker.fileName,
        emojis: sticker.emojis,
        accessibilityText: sticker.accessibilityText,
        sizeBytes: buffer.length,
        sha256: sha256(buffer),
        position,
      },
    });
  }

  console.log(`Seeded ${demoPack.name}`);
  console.log(`Login: ${demoUser.email} / ${demoUser.password}`);
}

function loadEnvFile(path) {
  if (!existsSync(path)) {
    return;
  }

  for (const line of readFileSync(path, 'utf8').split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!match || process.env[match[1]] !== undefined) {
      continue;
    }
    process.env[match[1]] = match[2].replace(/^["']|["']$/g, '');
  }
}

async function renderSticker(sticker) {
  const svg = `
    <svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
      <rect width="512" height="512" fill="none"/>
      <path d="M80 172 C80 100 158 64 256 64 C354 64 432 100 432 172 L432 340 C432 412 354 448 256 448 C158 448 80 412 80 340 Z" fill="${sticker.fill}"/>
      <path d="M116 156 C158 104 238 96 306 114 C252 124 196 154 158 206 C134 238 122 282 128 332 C96 288 92 202 116 156 Z" fill="${sticker.accent}" opacity="0.28"/>
      <text x="256" y="292" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="108" font-weight="800" fill="#111827">${sticker.label}</text>
    </svg>
  `;

  return sharp(Buffer.from(svg)).resize(512, 512, { fit: 'contain' }).webp({ quality: 82 }).toBuffer();
}

async function renderTrayIcon() {
  const svg = `
    <svg width="96" height="96" viewBox="0 0 96 96" xmlns="http://www.w3.org/2000/svg">
      <rect width="96" height="96" rx="22" fill="#111827"/>
      <path d="M24 28 H72 V68 H24 Z" fill="#f9fafb"/>
      <path d="M32 38 H64" stroke="#14b8a6" stroke-width="8" stroke-linecap="round"/>
      <path d="M32 54 H56" stroke="#ef4444" stroke-width="8" stroke-linecap="round"/>
    </svg>
  `;

  return sharp(Buffer.from(svg)).resize(96, 96).webp({ quality: 85 }).toBuffer();
}

function sha256(buffer) {
  return createHash('sha256').update(buffer).digest('hex');
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
